In [1]:
# =========================
# Employee Attrition Prediction
# =========================
# Dieses Notebook analysiert HR-Daten und sagt Mitarbeiterfluktuation (Attrition) vorher.
# Perfekt für Bewerbungen im Bereich People Analytics / Data Science.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [3]:
# CSV-Datei in den 'data' Ordner legen
df = pd.read_csv("data/WA_Fn-UseC_-HR-Employee-Attrition.csv")

# Erste Zeilen ansehen
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [8]:
# Struktur der Daten
df.info()

# Statistische Zusammenfassung
df.describe()

# Nullwerte checken
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   str
 2   BusinessTravel            1470 non-null   str
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   str
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   str
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   str
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   str
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   str
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   str
 22  OverTime                  1470 non-null   str
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), str(9)
memory usage: 402.1 KB

Age                         0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [14]:
# Zielvariable: Attrition Ja/Nein
y = df["Attrition"].map({"Yes": 1, "No": 0})

# Features
X = df.drop("Attrition", axis=1)

# Kategorische Variablen umwandeln
X = pd.get_dummies(X)

# Daten checken
X.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,False,False,True,False,False,False,True,True,False,True
1,49,279,8,1,1,2,3,61,2,2,...,False,True,False,False,False,True,False,True,True,False
2,37,1373,2,2,1,4,4,92,2,1,...,False,False,False,False,False,False,True,True,False,True
3,33,1392,3,4,1,5,4,56,3,1,...,False,True,False,False,False,True,False,True,False,True
4,27,591,2,1,1,7,1,40,3,1,...,False,False,False,False,False,True,False,True,True,False

In [15]:
X.info()

<class 'pandas.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 55 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   DailyRate                          1470 non-null   int64
 2   DistanceFromHome                   1470 non-null   int64
 3   Education                          1470 non-null   int64
 4   EmployeeCount                      1470 non-null   int64
 5   EmployeeNumber                     1470 non-null   int64
 6   EnvironmentSatisfaction            1470 non-null   int64
 7   HourlyRate                         1470 non-null   int64
 8   JobInvolvement                     1470 non-null   int64
 9   JobLevel                           1470 non-null   int64
 10  JobSatisfaction                    1470 non-null   int64
 11  MonthlyIncome                      1470 non-null   int64
 12  MonthlyRate                        1470 non-null   int64
 13  NumCompaniesWorked                 1470 non-null   int64
 14  PercentSalaryHike                  1470 non-null   int64
 15  PerformanceRating                  1470 non-null   int64
 16  RelationshipSatisfaction           1470 non-null   int64
 17  StandardHours                      1470 non-null   int64
 18  StockOptionLevel                   1470 non-null   int64
 19  TotalWorkingYears                  1470 non-null   int64
 20  TrainingTimesLastYear              1470 non-null   int64
 21  WorkLifeBalance                    1470 non-null   int64
 22  YearsAtCompany                     1470 non-null   int64
 23  YearsInCurrentRole                 1470 non-null   int64
 24  YearsSinceLastPromotion            1470 non-null   int64
 25  YearsWithCurrManager               1470 non-null   int64
 26  BusinessTravel_Non-Travel          1470 non-null   bool
 27  BusinessTravel_Travel_Frequently   1470 non-null   bool
 28  BusinessTravel_Travel_Rarely       1470 non-null   bool
 29  Department_Human Resources         1470 non-null   bool
 30  Department_Research & Development  1470 non-null   bool
 31  Department_Sales                   1470 non-null   bool
 32  EducationField_Human Resources     1470 non-null   bool
 33  EducationField_Life Sciences       1470 non-null   bool
 34  EducationField_Marketing           1470 non-null   bool
 35  EducationField_Medical             1470 non-null   bool
 36  EducationField_Other               1470 non-null   bool
 37  EducationField_Technical Degree    1470 non-null   bool
 38  Gender_Female                      1470 non-null   bool
 39  Gender_Male                        1470 non-null   bool
 40  JobRole_Healthcare Representative  1470 non-null   bool
 41  JobRole_Human Resources            1470 non-null   bool
 42  JobRole_Laboratory Technician      1470 non-null   bool
 43  JobRole_Manager                    1470 non-null   bool
 44  JobRole_Manufacturing Director     1470 non-null   bool
 45  JobRole_Research Director          1470 non-null   bool
 46  JobRole_Research Scientist         1470 non-null   bool
 47  JobRole_Sales Executive            1470 non-null   bool
 48  JobRole_Sales Representative       1470 non-null   bool
 49  MaritalStatus_Divorced             1470 non-null   bool
 50  MaritalStatus_Married              1470 non-null   bool
 51  MaritalStatus_Single               1470 non-null   bool
 52  Over18_Y                           1470 non-null   bool
 53  OverTime_No                        1470 non-null   bool
 54  OverTime_Yes                       1470 non-null   bool
dtypes: bool(29), int64(26)
memory usage: 340.4 KB

In [16]:
# Trainings- und Testdaten
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Random Forest Classifier
model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Vorhersage auf Testdaten
y_pred = model.predict(X_test)

In [17]:
# Precision, Recall, Accuracy ausgeben
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.99      0.93       255
           1       0.67      0.15      0.25        39

    accuracy                           0.88       294
   macro avg       0.78      0.57      0.59       294
weighted avg       0.86      0.88      0.84       294